### ISSUE TITLE
NextDNS geolocation not working

### ISSUE THREAD

**Issue by thewan056** [celzero/brave-android-app#86]
When using NextDNS as a custom DNS resolver, it doesn't connect to the nearest node. I hope you could work it out with NextDNS to fix this.

**Comment by ignoramous** [comment]
I think they do something special in their app to choose servers according to geo-location. Otherwise, the default is that they rely on `anycast` to do its bit in routing the user to the closest location (latency-wise, in theory at least).

From looking at what they do with https://ping.nextdns.io/

You could try:

`dns1.nextdns.io/<your-config>` or `dns2.nextdns.io/<your-config>` to explicitly hit what they call `primary` and `secondary` servers (these seem to be based on latencies?)

or

https://router.nextdns.io/ and use the hostname it prints to hit the (geographically) nearest endpoint. It'd look something like `https://ipv4-gc-bom-1.edge.nextdns.io/<your-config>`.

**Comment by ignoramous** [comment]
Unfortunately, we can't do the above in our the app because we aren't affiliated with nextdns and cannot rely on their undocumented APIs.

**Comment by thewan056** [comment]
My apologies. I assumed that since their CLI client is open source, I thought maybe you could get it to work from there.

Thanks for the suggestions. The 1st suggestion didn't work. Instead it became worse by connecting directly to what I assume literally are their primary and secondary servers.

Your 2nd one:

> https://router.nextdns.io/ and use the hostname it prints to hit the (geographically) nearest endpoint. It'd look something like https://ipv4-gc-bom-1.edge.nextdns.io/<your-config>.

This worked for me. I managed to connect directly to my local node and experience better pings now. Though I'm not sure if NextDNS allows their users to use it this way.

Since there is a workaround I'll close this then.

**Comment by ignoramous** [comment]
No problem. And I think you're right about the CLI, see: [nextdns/nextdns-cli/7106d9b4a2/run.go#L414](https://github.com/nextdns/nextdns/blob/7106d9b4a265f93e32ff1b842e87e90cea7e480e/run.go#L414)

If I can establish for a fact that nextdns wouldn't change `router.nextdns.io` API from underneath us, I can definitely consider adding special logic for them (because they are a special project).

**Comment by ignoramous** [comment]
Opened: https://github.com/nextdns/nextdns/issues/324

**Comment by ignoramous** [comment]
As suspected, nextdns isn't willing to guarantee the API would continue to work.

**Comment by thewan056** [comment]
Yeah, I think so too.

I've discovered something while testing out Adguard Home recently, to act purely as a resolver, no filters configured, for clients on my local network that don't have native support for DoH/DoT together with NextDNS. I also found that I wasn't connecting to my nearest location by default. However, by configuring the Boostrap DNS servers to point to NextDNS , `45.90.28.211` and `45.90.30.211` only instead of the default ones, I got it to work. Seeing that from Issue #94 you are already considering to add the ability to customize it. Once its available, I would gladly try this out.
